{"id":4033,"date":"2020-09-21T22:57:39","date_gmt":"2020-09-21T17:27:39","guid":{"rendered":"https:\/\/golangbyexamples.com\/?p=4033"},"modified":"2020-09-21T22:57:58","modified_gmt":"2020-09-21T17:27:58","slug":"recover-example-go","status":"publish","type":"post","link":"https:\/\/golangbyexamples.com\/recover-example-go\/","title":{"rendered":"Example of Recover Function in Go (Golang)"},"content":{"rendered":"\n<div id=\"ez-toc-container\" class=\"ez-toc-v2_0_17 counter-hierarchy counter-decimal ez-toc-light-blue\">\n<div class=\"ez-toc-title-container\">\n<p class=\"ez-toc-title\">Table of Contents<\/p>\n<span class=\"ez-toc-title-toggle\"><a class=\"ez-toc-pull-right ez-toc-btn ez-toc-btn-xs ez-toc-btn-default ez-toc-toggle\" style=\"display: none;\"><i class=\"ez-toc-glyphicon ez-toc-icon-toggle\"><\/i><\/a><\/span><\/div>\n<nav><ul class=\"ez-toc-list ez-toc-list-level-1\"><li class=\"ez-toc-page-1 ez-toc-heading-level-1\"><a class=\"ez-toc-link ez-toc-heading-1\" href=\"https:\/\/golangbyexamples.com\/recover-example-go\/#Overview\" title=\"Overview\">Overview<\/a><\/li><li class=\"ez-toc-page-1 ez-toc-heading-level-1\"><a class=\"ez-toc-link ez-toc-heading-2\" href=\"https:\/\/golangbyexamples.com\/recover-example-go\/#Example\" title=\"Example\">Example<\/a><\/li><\/ul><\/nav><\/div>\n<h1 class=\"wp-block-heading\"><span class=\"ez-toc-section\" id=\"Overview\"><\/span><strong>Overview<\/strong><span class=\"ez-toc-section-end\"><\/span><\/h1>\n\n\n\n<p class=\"has-medium-font-size\">Go provides a built-in function <strong>recover<\/strong> for recovering from a panic. Below is the signature of this function<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-\">func recover() interface{}<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\"><strong>defer<\/strong> function is the only function that is called after the <strong>panic<\/strong>. So it makes sense to put the <strong>recover<\/strong> function in the <strong>defer<\/strong> function only. If the <strong>recover<\/strong>\u00a0function is not within the\u00a0defer function then it will not stop <strong>panic<\/strong>.<\/p>\n\n\n\n<h1 class=\"wp-block-heading\"><span class=\"ez-toc-section\" id=\"Example\"><\/span><strong>Example<\/strong><span class=\"ez-toc-section-end\"><\/span><\/h1>\n\n\n\n<p class=\"has-medium-font-size\">Let&#8217;s see an example of recover<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">package main\n\nimport \"fmt\"\n\nfunc main() {\n\n\ta := []string{\"a\", \"b\"}\n\tcheckAndPrint(a, 2)\n\tfmt.Println(\"Exiting normally\")\n}\n\nfunc checkAndPrint(a []string, index int) {\n\tdefer handleOutOfBounds()\n\tif index > (len(a) - 1) {\n\t\tpanic(\"Out of bound access for slice\")\n\t}\n\tfmt.Println(a[index])\n}\n\nfunc handleOutOfBounds() {\n\tif r := recover(); r != nil {\n\t\tfmt.Println(\"Recovering from panic:\", r)\n\t}\n}<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\"><strong>Output<\/strong><\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">Recovering from panic: Out of bound access for slice\nExiting normally<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">In the above program we have a function <strong>checkAndPrint<\/strong> which checks and prints slice element at an index passed in the argument. If the index passed is greater than the length of the array\u00a0then the program panics.\u00a0 We have added a defer function named <strong>handleOutIfBounds<\/strong> as well at the start of the function <strong>checkAndPrint<\/strong>.\u00a0 \u00a0This function\u00a0 contains\u00a0 the\u00a0 call to recover function\u00a0as below<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">if r := recover(); r != nil {\n    fmt.Println(\"Recovering from panic:\", r)\n}<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">The <strong>recover<\/strong> function will catch the panic and we can also print the message from the panic.\u00a0<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">Recovering from panic: Out of bound access for slice<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">After the recover function the program continues and the control returns to the called function which is\u00a0 <strong>main<\/strong> here. That is why we get output as<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">Exiting normally<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">The\u00a0recover function\u00a0 returns the value which was passed\u00a0to the panic function. Therefore it is a good practice to check the return value of the recover function. If the return value is non nil then panic did not happen and recover function was not called with the panic. That is why we have below code in the\u00a0 defer function <strong>handleOutofBounds<\/strong><\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">if r := recover(); r != nil <\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">Here if <strong>r<\/strong> is nil then panic did not happened. So if there is no panic then call to recover will return nil<\/p>\n\n\n\n<p class=\"has-medium-font-size\">Note that if\u00a0the defer function and recover function is not called from the panicking function then it that case also panic can be recovered in the called function as well. Infact it is possible to recover from panic subsequently up in the chain of call stack.<\/p>\n\n\n\n<p class=\"has-medium-font-size\">Let&#8217;s see an example of this<\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">package main\n\nimport \"fmt\"\n\nfunc main() {\n    a := []string{\"a\", \"b\"}\n    checkAndPrintWithRecover(a, 2)\n    fmt.Println(\"Exiting normally\")\n}\nfunc checkAndPrintWithRecover(a []string, index int) {\n    defer handleOutOfBounds()\n    checkAndPrint(a, 2)\n}\nfunc checkAndPrint(a []string, index int) {\n    if index > (len(a) - 1) {\n        panic(\"Out of bound access for slice\")\n    }\n    fmt.Println(a[index])\n}\nfunc handleOutOfBounds() {\n    if r := recover(); r != nil {\n        fmt.Println(\"Recovering from panic:\", r)\n    }\n}<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\"><strong>Output<\/strong><\/p>\n\n\n\n<pre class=\"wp-block-prismatic-blocks\"><code class=\"language-go\">Recovering from panic: Out of bound access for slice\nExiting normally<\/code><\/pre>\n\n\n\n<p class=\"has-medium-font-size\">Above program is quite same as previous program other than we have a additional function <strong>checkAndPrintWithRecover <\/strong>which contains the call to&nbsp;<\/p>\n\n\n\n<ul class=\"has-medium-font-size wp-block-list\"><li>defer function with recover which is <strong>handleOutOfBounds<\/strong><\/li><li>calls&nbsp;<strong>checkAndPrint <\/strong>function<\/li><\/ul>\n\n\n\n<p class=\"has-medium-font-size\"><strong><\/strong>So basically <strong>checkAndPrint<\/strong> function raises the panic but doesn&#8217;t have the recover function instead call to recover lies in the <strong>checkAndPrintWithRecover <\/strong>function. But still the program is able to recover from panic&nbsp; as panic can also be recovered in the called function also and subsequently in the chain as well<\/p>\n","protected":false},"excerpt":{"rendered":"<p>Table of Contents OverviewExample Overview Go provides a built-in function recover for recovering from a panic. Below is the signature of this function defer function is the only function that is called&#8230;<\/p>\n","protected":false},"author":1,"featured_media":0,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"standard","meta":{"spay_email":"","footnotes":"","jetpack_publicize_message":"","jetpack_is_tweetstorm":false},"categories":[1],"tags":[3,4],"class_list":["post-4033","post","type-post","status-publish","format-standard","hentry","category-tech","tag-go","tag-golang"],"yoast_head":"<!-- This site is optimized with the Yoast SEO plugin v22.7 - https:\/\/yoast.com\/wordpress\/plugins\/seo\/ -->\n<title>Example of Recover Function in Go (Golang) - Welcome To Golang By Example<\/title>\n<meta name=\"robots\" content=\"index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1\" \/>\n<link rel=\"canonical\" href=\"https:\/\/golangbyexamples.com\/recover-example-go\/\" \/>\n<meta property=\"og:locale\" content=\"en_US\" \/>\n<meta property=\"og:type\" content=\"article\" \/>\n<meta property=\"og:title\" content=\"Example of Recover Function in Go (Golang) - Welcome To Golang By Example\" \/>\n<meta property=\"og:description\" content=\"Table of Contents OverviewExample Overview Go provides a built-in function recover for recovering from a panic. Below is the signature of this function defer function is the only function that is called...\" \/>\n<meta property=\"og:url\" content=\"https:\/\/golangbyexamples.com\/recover-example-go\/\" \/>\n<meta property=\"og:site_name\" content=\"Welcome To Golang By Example\" \/>\n<meta property=\"article:published_time\" content=\"2020-09-21T17:27:39+00:00\" \/>\n<meta property=\"article:modified_time\" content=\"2020-09-21T17:27:58+00:00\" \/>\n<meta name=\"author\" content=\"admin\" \/>\n<meta name=\"twitter:card\" content=\"summary_large_image\" \/>\n<meta name=\"twitter:label1\" content=\"Written by\" \/>\n\t<meta name=\"twitter:data1\" content=\"admin\" \/>\n\t<meta name=\"twitter:label2\" content=\"Est. reading time\" \/>\n\t<meta name=\"twitter:data2\" content=\"3 minutes\" \/>\n<script type=\"application\/ld+json\" class=\"yoast-schema-graph\">{\"@context\":\"https:\/\/schema.org\",\"@graph\":[{\"@type\":\"WebPage\",\"@id\":\"https:\/\/golangbyexamples.com\/recover-example-go\/\",\"url\":\"https:\/\/golangbyexamples.com\/recover-example-go\/\",\"name\":\"Example of Recover Function in Go (Golang) - Welcome To Golang By Example\",\"isPartOf\":{\"@id\":\"https:\/\/golangbyexamples.com\/#website\"},\"datePublished\":\"2020-09-21T17:27:39+00:00\",\"dateModified\":\"2020-09-21T17:27:58+00:00\",\"author\":{\"@id\":\"https:\/\/golangbyexamples.com\/#\/schema\/person\/8833ea7638dafd763cb1db6c0ca4576f\"},\"breadcrumb\":{\"@id\":\"https:\/\/golangbyexamples.com\/recover-example-go\/#breadcrumb\"},\"inLanguage\":\"en-US\",\"potentialAction\":[{\"@type\":\"ReadAction\",\"target\":[\"https:\/\/golangbyexamples.com\/recover-example-go\/\"]}]},{\"@type\":\"BreadcrumbList\",\"@id\":\"https:\/\/golangbyexamples.com\/recover-example-go\/#breadcrumb\",\"itemListElement\":[{\"@type\":\"ListItem\",\"position\":1,\"name\":\"Home\",\"item\":\"https:\/\/golangbyexamples.com\/\"},{\"@type\":\"ListItem\",\"position\":2,\"name\":\"Example of Recover Function in Go (Golang)\"}]},{\"@type\":\"WebSite\",\"@id\":\"https:\/\/golangbyexamples.com\/#website\",\"url\":\"https:\/\/golangbyexamples.com\/\",\"name\":\"Welcome To Golang By Example\",\"description\":\"\",\"potentialAction\":[{\"@type\":\"SearchAction\",\"target\":{\"@type\":\"EntryPoint\",\"urlTemplate\":\"https:\/\/golangbyexamples.com\/?s={search_term_string}\"},\"query-input\":\"required name=search_term_string\"}],\"inLanguage\":\"en-US\"},{\"@type\":\"Person\",\"@id\":\"https:\/\/golangbyexamples.com\/#\/schema\/person\/8833ea7638dafd763cb1db6c0ca4576f\",\"name\":\"admin\",\"image\":{\"@type\":\"ImageObject\",\"inLanguage\":\"en-US\",\"@id\":\"https:\/\/golangbyexamples.com\/#\/schema\/person\/image\/\",\"url\":\"https:\/\/secure.gravatar.com\/avatar\/?s=96&d=mm&r=g\",\"contentUrl\":\"https:\/\/secure.gravatar.com\/avatar\/?s=96&d=mm&r=g\",\"caption\":\"admin\"},\"url\":\"https:\/\/golangbyexamples.com\/author\/admin\/\"}]}<\/script>\n<!-- \/ Yoast SEO plugin. -->","yoast_head_json":{"title":"Example of Recover Function in Go (Golang) - Welcome To Golang By Example","robots":{"index":"index","follow":"follow","max-snippet":"max-snippet:-1","max-image-preview":"max-image-preview:large","max-video-preview":"max-video-preview:-1"},"canonical":"https:\/\/golangbyexamples.com\/recover-example-go\/","og_locale":"en_US","og_type":"article","og_title":"Example of Recover Function in Go (Golang) - Welcome To Golang By Example","og_description":"Table of Contents OverviewExample Overview Go provides a built-in function recover for recovering from a panic. Below is the signature of this function defer function is the only function that is called...","og_url":"https:\/\/golangbyexamples.com\/recover-example-go\/","og_site_name":"Welcome To Golang By Example","article_published_time":"2020-09-21T17:27:39+00:00","article_modified_time":"2020-09-21T17:27:58+00:00","author":"admin","twitter_card":"summary_large_image","twitter_misc":{"Written by":"admin","Est. reading time":"3 minutes"},"schema":{"@context":"https:\/\/schema.org","@graph":[{"@type":"WebPage","@id":"https:\/\/golangbyexamples.com\/recover-example-go\/","url":"https:\/\/golangbyexamples.com\/recover-example-go\/","name":"Example of Recover Function in Go (Golang) - Welcome To Golang By Example","isPartOf":{"@id":"https:\/\/golangbyexamples.com\/#website"},"datePublished":"2020-09-21T17:27:39+00:00","dateModified":"2020-09-21T17:27:58+00:00","author":{"@id":"https:\/\/golangbyexamples.com\/#\/schema\/person\/8833ea7638dafd763cb1db6c0ca4576f"},"breadcrumb":{"@id":"https:\/\/golangbyexamples.com\/recover-example-go\/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https:\/\/golangbyexamples.com\/recover-example-go\/"]}]},{"@type":"BreadcrumbList","@id":"https:\/\/golangbyexamples.com\/recover-example-go\/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/golangbyexamples.com\/"},{"@type":"ListItem","position":2,"name":"Example of Recover Function in Go (Golang)"}]},{"@type":"WebSite","@id":"https:\/\/golangbyexamples.com\/#website","url":"https:\/\/golangbyexamples.com\/","name":"Welcome To Golang By Example","description":"","potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https:\/\/golangbyexamples.com\/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"en-US"},{"@type":"Person","@id":"https:\/\/golangbyexamples.com\/#\/schema\/person\/8833ea7638dafd763cb1db6c0ca4576f","name":"admin","image":{"@type":"ImageObject","inLanguage":"en-US","@id":"https:\/\/golangbyexamples.com\/#\/schema\/person\/image\/","url":"https:\/\/secure.gravatar.com\/avatar\/?s=96&d=mm&r=g","contentUrl":"https:\/\/secure.gravatar.com\/avatar\/?s=96&d=mm&r=g","caption":"admin"},"url":"https:\/\/golangbyexamples.com\/author\/admin\/"}]}},"jetpack_featured_media_url":"","jetpack_publicize_connections":[],"jetpack_sharing_enabled":true,"jetpack_shortlink":"https:\/\/wp.me\/paOs1b-133","amp_validity":null,"amp_enabled":true,"_links":{"self":[{"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/posts\/4033","targetHints":{"allow":["GET"]}}],"collection":[{"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/comments?post=4033"}],"version-history":[{"count":2,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/posts\/4033\/revisions"}],"predecessor-version":[{"id":4035,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/posts\/4033\/revisions\/4035"}],"wp:attachment":[{"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/media?parent=4033"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/categories?post=4033"},{"taxonomy":"post_tag","embeddable":true,"href":"https:\/\/golangbyexamples.com\/wp-json\/wp\/v2\/tags?post=4033"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}}